export const Action_Type = {
  IS_SIGN_SHOW: "IS_SIGN_SHOW",
  IS_SIGNUP_SHOW: "IS_SIGNUP_SHOW",
  READ_PRODUCT: "READ_PRODUCT",
  API_LOADING: "API_LOADING",
  USER_DETAILS: "USER_DETAILS",
  READ_BID_LIST: "READ_BID_LIST",
  SELL_PRODUCT: "SELL_PRODUCT",
  ROUTER: "ROUTER",
  SUCCESS_MODAL: "SUCCESS_MODAL",
  READ_PRODUCT_BY_ID: "READ_PRODUCT_BY_ID",
  READ_BID_LIST_BY_ID: "READ_BID_LIST_BY_ID",
  OPEN_SELL_MODAL:"OPEN_SELL_MODAL"
};
